import Head from "next/head";
import {ReactDOM} from "react";
import Header from "@/organisms/Header";
import Button from "@/atoms/button";
import {useRouter} from "next/router";

type Props ={
  children : JSX.Element | string
}

const DefaultLayout = ({children} : Props) => {
  const router = useRouter()
  return(
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Header />
          <div className={'container mx-auto py-5 px-3'}>
            {
              router.pathname !== '/' && (
                <div className={'mb-5'}>
                  <Button handleClick={()=>router.back()}>Go back</Button>
                </div>
              )
            }

            <div className={'shadow-2xl rounded-2xl p-5'}>
              {children}
            </div>

          </div>
        </main>
      </>
  )
}
export default DefaultLayout
